"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import * as z from "zod";
import { Button } from "@/components/ui/button";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import type { FinalStock, BOMRow, ProcessingStageName } from "@/lib/types";
import { useEffect, useState } from "react";
import { PlaceHolderImages } from "@/lib/placeholder-images";
import { BOMEditor } from "@/components/bom-editor";
import { ImageUpload } from "@/components/image-upload";
import { ManufacturingStagesSelector } from "@/components/manufacturing-stages-selector";
import { Checkbox } from "@/components/ui/checkbox";
import { uploadImage, deleteImage } from "@/lib/firebase/storage";
import { useToast } from "@/hooks/use-toast";

const formSchema = z.object({
  productId: z.string().min(1, "Please enter a Product ID."),
  name: z.string().min(1, "Please enter a name."),
  sku: z.string().min(1, "Please enter a SKU."),
  price: z.coerce.number().min(0, "Price must be 0 or greater."),
  gstRate: z.coerce.number().min(0, "GST Rate must be 0 or greater."),
  threshold: z.coerce.number().min(0, "Threshold must be 0 or greater.").default(0),
  imageUrl: z.string().optional(),
  imageHint: z.string(),
  hasManufacturingDetails: z.boolean().default(true),
});

interface CreateProductFormProps {
  onProductCreated: (product: FinalStock) => void;
}

export function CreateProductForm({
  onProductCreated,
}: CreateProductFormProps) {
  const [isClient, setIsClient] = useState(false);
  const [bomRows, setBomRows] = useState<BOMRow[]>([]);
  const [manufacturingStages, setManufacturingStages] = useState<ProcessingStageName[]>([]);
  const { toast } = useToast();
  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      productId: "",
      name: "",
      sku: "",
      price: 0,
      gstRate: 0,
      threshold: 0,
      imageUrl: "",
      imageHint: "",
      hasManufacturingDetails: true,
    },
  });

  useEffect(() => {
    setIsClient(true);

    const randomPlaceholder =
      PlaceHolderImages[Math.floor(Math.random() * PlaceHolderImages.length)];
    if (randomPlaceholder) {
      form.setValue("imageHint", randomPlaceholder.imageHint);
    }
  }, [form]);

  const handleMeasurementSketchUpload = async (
    event: React.ChangeEvent<HTMLInputElement>,
    currentUrl?: string,
  ) => {
    const file = event.target.files?.[0];
    if (!file) return;

    const allowedTypes = ["image/jpeg", "image/jpg", "image/png"];
    if (!allowedTypes.includes(file.type)) {
      toast({
        variant: "destructive",
        title: "Invalid File",
        description: "Please upload a JPEG or PNG image for the measurement sketch.",
      });
      return;
    }

    try {
      if (currentUrl) {
        try {
          await deleteImage(currentUrl);
        } catch (error) {
          console.warn("[CreateProductForm] Failed to delete existing measurement sketch:", error);
        }
      }

      const url = await uploadImage(file, "measurement-sketches");
      form.setValue("measurementSketch" as any, url);
    } catch (error) {
      console.error("[CreateProductForm] Measurement sketch upload failed:", error);
      toast({
        variant: "destructive",
        title: "Upload Failed",
        description:
          error instanceof Error
            ? error.message
            : "Failed to upload measurement sketch image.",
      });
    }
  };

  function onSubmit(values: z.infer<typeof formSchema>) {
    const { hasManufacturingDetails } = values;

    let validBomRows: BOMRow[] = [];

    if (hasManufacturingDetails) {
      // Validate manufacturing stages selection
      if (manufacturingStages.length === 0) {
        form.setError("root", {
          type: "manual",
          message: "Please select at least one manufacturing stage.",
        });
        return;
      }

      // Validate BOM rows against selected stages
      validBomRows = bomRows.filter(
        (row) => row.raw_material_id && row.stage && row.qty_per_piece > 0,
      );

      // Check if BOM entries are only for selected stages
      const invalidBomRows = validBomRows.filter(
        (row) => !manufacturingStages.includes(row.stage),
      );

      if (invalidBomRows.length > 0) {
        form.setError("root", {
          type: "manual",
          message: `BOM entries found for unselected stages: ${invalidBomRows
            .map((r) => r.stage)
            .join(", ")}. Please remove these entries or select the corresponding stages.`,
        });
        return;
      }
    }

    const measurementSketch = form.getValues("measurementSketch" as any) as
      | string
      | undefined;

    // Note: id will be generated by Firestore when document is created
    const newProduct: FinalStock = {
      id: "", // Temporary - will be replaced by Firestore-generated ID
      ...values,
      manufacturingStages: hasManufacturingDetails ? manufacturingStages : [],
      imageUrl:
        values.imageUrl || `https://picsum.photos/seed/${values.name}/400/300`,
      measurementSketch,
      bom_per_piece:
        hasManufacturingDetails && validBomRows.length > 0
          ? validBomRows
          : undefined,
      batches: [], // Initialize with empty batches array
      createdAt: new Date().toISOString(),
    };
    onProductCreated(newProduct);
  }

  if (!isClient) {
    return null;
  }

  const hasManufacturingDetails = form.watch("hasManufacturingDetails");

  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6 pt-4">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <FormField
              control={form.control}
              name="productId"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Product ID</FormLabel>
                  <FormControl>
                    <Input placeholder="e.g., PROD-1001" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="name"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Product Name</FormLabel>
                  <FormControl>
                    <Input placeholder="e.g., Model X Mainframe" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="sku"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>SKU</FormLabel>
                  <FormControl>
                    <Input placeholder="e.g., MX-MF-001" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <FormField
              control={form.control}
              name="price"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Unit Price (excl. GST)</FormLabel>
                  <FormControl>
                    <Input type="number" placeholder="0.00" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="gstRate"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>GST Rate (%)</FormLabel>
                  <FormControl>
                    <Input type="number" placeholder="0" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="threshold"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Low Stock Threshold</FormLabel>
                  <FormControl>
                    <Input type="number" placeholder="0" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
          </div>
          <FormField
            control={form.control}
            name="imageUrl"
            render={({ field }) => (
              <FormItem>
                <FormControl>
                  <ImageUpload
                    value={field.value}
                    onChange={field.onChange}
                    folder="products"
                    placeholder="Upload product image"
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name={"measurementSketch" as any}
            render={({ field }) => (
              <FormItem>
                <FormLabel>Measurement Sketch</FormLabel>
                <FormControl>
                  <div className="flex items-center gap-4">
                    <Input
                      type="file"
                      accept="image/jpeg,image/jpg,image/png"
                      onChange={(event) =>
                        handleMeasurementSketchUpload(event, field.value || undefined)
                      }
                    />
                    {field.value ? (
                      <img
                        src={field.value}
                        alt="Measurement sketch preview"
                        className="h-12 w-12 rounded border object-contain"
                      />
                    ) : (
                      <span className="text-xs text-muted-foreground">No Image</span>
                    )}
                  </div>
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="hasManufacturingDetails"
            render={({ field }) => (
              <FormItem className="flex flex-row items-center space-x-2 space-y-0 border-t pt-4">
                <FormControl>
                  <Checkbox
                    checked={field.value}
                    onCheckedChange={(checked) => field.onChange(checked === true)}
                  />
                </FormControl>
                <FormLabel className="font-medium">
                  To be Manufactured
                </FormLabel>
              </FormItem>
            )}
          />

          {hasManufacturingDetails && (
            <>
              {/* Manufacturing Stages Selector */}
              <div className="border-t pt-6">
                <ManufacturingStagesSelector
                  selectedStages={manufacturingStages}
                  onStagesChange={setManufacturingStages}
                />
              </div>

              {/* BOM Editor */}
              <div className="border-t pt-6">
                <BOMEditor
                  bomRows={bomRows}
                  onBOMChange={setBomRows}
                  productName={form.watch("name")}
                  selectedStages={manufacturingStages}
                />
              </div>
            </>
          )}

          {/* Form Errors */}
          {form.formState.errors.root && (
            <div className="p-3 bg-red-50 border border-red-200 rounded-lg">
              <p className="text-sm text-red-800">{form.formState.errors.root.message}</p>
            </div>
          )}

          <div className="flex justify-end">
            <Button type="submit">Add Product</Button>
          </div>
      </form>
    </Form>
  );
}
